name: Update API documentation
on:
  schedule:
    # runs every day at 02:02 UTC
    - cron: '2 2 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache .m2 repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
      - name: Build tools
        run: ./mvnw -B package -Pcli
      - name: Parse web API
        run: ./scripts/parse-web-api.sh
      - name: Generate Open API
        run: ./scripts/generate-open-api.sh
      - name: Generate TypeScript
        run: ./scripts/generate-ts.sh
      # No need to run the tests here, they also run in the created PR
      # - name: Test
      #   run: ./mvnw -B clean verify
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          # Use a PAT so GitHub actions are triggered on the PR
          token: ${{ secrets.GH_REPO_TOKEN }}
          commit-message: 'Automated Spotify Web API update'
          branch: 'automated-api-documentation-update'
          delete-branch: true
          base: master
          author: 'sonallux <13821543+sonallux@users.noreply.github.com>'
          title: 'Update Spotify Web API'
          body: 'Automated Spotify Web API update from
            [actions run](https://github.com/sonallux/spotify-web-api/actions/runs/${{ github.run_id }})'
      - name: Check outputs
        run: 'echo "Pull Request ${{ steps.cpr.outputs.pull-request-operation }}: ${{ steps.cpr.outputs.pull-request-url }}"'
      - name: Comment on PR
        if: steps.cpr.outputs.pull-request-operation == 'created'
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
              issue_number: ${{ steps.cpr.outputs.pull-request-number }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '@sonallux the Spotify Web API has been updated!'
            })
